### ISSUE TITLE
Use of puppet-archive instead of voxpupuli /puppet-wget 

### ISSUE THREAD

**Issue by bhamilton** [attachmentgenie/attachmentgenie-mailhog#4]
This module officially depends on maestrodev-wget (>=1.7.3 <2.0.0) but wget was [adopted and deprecated](https://github.com/voxpupuli/puppet-wget) by Vox Pupuli in favor of the archive module. Is there any chance a new release could be released using archive instead. 

I've not notice any breaks with this module and Puppet 6.x, but that is the reason I noticed this.

**Comment by attachmentgenie** [comment]
i just released v4.0.0 to the forge that has the new dependency on archive and is now fully pdk-ized
